version: 2

models:
  - name: stg_yellow_trips
    columns:
      - name: vendor_id
        tests:
          - not_null
      - name: pickup_datetime
        tests:
          - not_null

  - name: fact_trips
    columns:
      - name: pickup_location_id
        tests:
          - relationships:
              to: ref('dim_taxi_zone')
              field: location_id
      - name: dropoff_location_id
        tests:
          - relationships:
              to: ref('dim_taxi_zone')
              field: location_id
      - name: payment_type
        tests:
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6]
              quote: false

  - name: mart_kpis_daily
    columns:
      - name: pickup_date
        tests:
          - unique
          - not_null

  - name: mart_kpis_hourly
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - pickup_date
            - pickup_hour

  - name: mart_kpis_by_zone_daily
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - pickup_date
            - pickup_location_id

