version: 2

sources:
  - name: raw
    database: analytics
    schema: raw
    tables:
      - name: yellow_trips
        description: "Raw yellow taxi trip data from NYC TLC Parquet files."
        loaded_at_field: load_timestamp
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 72, period: hour}
        columns:
          - name: tpep_pickup_datetime
            tests:
              - not_null
      
      - name: taxi_zone_lookup
        description: "Static lookup table for taxi zones."
